info:
  title: Swagger Petstore
openapi: 3.1.0
components:
  schemas:
    NullConst:
      description: |
        The value of this keyword MAY be null. 
        Use of this keyword is functionally equivalent to an "enum" (Section 6.1.2) with a single value.
        An instance validates successfully against this keyword if its value is equal to the value of the keyword.
      properties:
        withoutValue:
          const: 
    StringValueConst:
      description: its value is equal to the value of the keyword
      properties:
        foobar:
          const: "foobar"
          type: string
    NumberValueConst:
      description: its value is equal to the value of the keyword
      properties:
        foobar:
          const: 42
          type: number
    MixedValueTypeConst:
      description: This probably should fail miserably
      properties:
        foobar:
          const: "foobar"
          type: number

    Cat:
      title: Cat
      type: object
      properties:
        id:
          format: uuid
          title: Id
          type: string
        type:
          const: Cat
          title: Type
        meow:
          type: boolean
          title: Meowing prevalence
      required:
      - id
      - type
    Dog:
      title: Dog
      type: object
      properties:
        id:
          format: uuid
          title: Id
          type: string
        bark:
          type: number
          title: Barking frequency
        type:
          const: Dog
          title: Type
      required:
      - id
      - type
    Petstore:
      title: Petstore
      type: object
      description: A project is an analysis project. It has a name, an id, and has
        a dataset
      properties:
        id:
          title: Id
          type: integer
        pets:
          default: []
          items:
            discriminator:
              mapping:
                Cat: "#/components/schemas/Cat"
                Dog: "#/components/schemas/Dog"
              propertyName: type
            oneOf:
            - "$ref": "#/components/schemas/Cat"
            - "$ref": "#/components/schemas/Dog"
          title: Pets
          type: array
      required:
      - id

paths: {}
